name: absolute_sensor
description: "Get absolute sensor values from device for different sensors."
version: 1.0.1
repository: https://github.com/abdulrehmank7/absolute-sensor/tree/master/absolute_sensor
homepage: https://github.com/abdulrehmank7/absolute-sensor/tree/master/absolute_sensor
issue_tracker: https://github.com/abdulrehmank7/absolute-sensor/issues

topics:
  - sensor
  - absolute-sensor-values
  - gyroscope-sensor
  - android-sensor


environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.arkapp.absolute_sensor
        pluginClass: AbsoluteSensorPlugin
      ios:
        pluginClass: AbsoluteSensorPlugin
      web:
        pluginClass: AbsoluteSensorWeb
        fileName: absolute_sensor_web.dart
