name: absolute_sensor
description: "Get absolute sensor value from device different type of sensors"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.arkapp.absolute_sensor
        pluginClass: AbsoluteSensorPlugin
      ios:
        pluginClass: AbsoluteSensorPlugin
      web:
        pluginClass: AbsoluteSensorWeb
        fileName: absolute_sensor_web.dart
